title: 이승준
description: "이승준의 개발 블로그"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/MyFace.jpg"

# Social Links
#email: bj20020911@gmail.com
github_username: mine3873
# twitter_username: mine3873
instagram_username: 2_wlsjun
#linkedin_username: linkedin
#facebook_username: facebook

# External API

giscus_repo: "byanko55/jekyll-theme-satellite"
giscus_repoId: "R_kgDOJ6fqWg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOJ6fqWs4Cc7p7"
#giscus_repo: "mine3873/mine3873.github.io"
#giscus_repoId: "R_kgDOMI_1_g"
#giscus_category: "Q&A"
#giscus_categoryId: "DIC_kwDOMI_1_s4CgE9X"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
